### ISSUE TITLE
(FunctionClauseError) no function clause matching in Filterable.Params.cast_error_message/1

### ISSUE THREAD

**Issue by eduardomrocha** [omohokcoj/filterable#16]
This error happens when I try to cast a value that doesn't match any of the atoms in a list.

```elixir
filterable do
   field :status, cast: {:atom, [:accepted, :pending, :rejected]}
end
```

```bash
[info] GET /v1/trees
[debug] Processing with PetreeApiWeb.TreeController.index/2
  Parameters: %{"status" => "asdf"}
  Pipelines: [:api]
[info] Sent 500 in 1617ms
[error] #PID<0.466.0> running PetreeApiWeb.Endpoint (connection #PID<0.465.0>, stream id 1) terminated
Server: 127.0.0.1:4000 (http)
Request: GET /v1/trees?status=asdf
** (exit) an exception was raised:
	** (FunctionClauseError) no function clause matching in Filterable.Params.cast_error_message/1
		(filterable 0.7.3) lib/filterable/params.ex:229: Filterable.Params.cast_error_message([value: "asdf", cast: {:atom, [:accepted, :pending, :rejected]}])
		(filterable 0.7.3) lib/filterable/params.ex:191: Filterable.Params.cast/3
		(filterable 0.7.3) lib/filterable/params.ex:18: Filterable.Params.filter_value/2
		(filterable 0.7.3) lib/filterable.ex:107: anonymous fn/4 in Filterable.filter_values/3
		(filterable 0.7.3) lib/filterable/utils.ex:8: anonymous fn/3 in Filterable.Utils.reduce_with/3
		(elixir 1.10.4) lib/enum.ex:3686: Enumerable.List.reduce/3
		(elixir 1.10.4) lib/enum.ex:2161: Enum.reduce_while/3
		(filterable 0.7.3) lib/filterable.ex:93: Filterable.apply_filters/4
		(petree_api 0.1.0) lib/petree_api_web/controllers/tree_controller.ex:16: PetreeApiWeb.TreeController.index/2
		(petree_api 0.1.0) lib/petree_api_web/controllers/tree_controller.ex:1: PetreeApiWeb.TreeController.action/2
		(petree_api 0.1.0) lib/petree_api_web/controllers/tree_controller.ex:1: PetreeApiWeb.TreeController.phoenix_controller_pipeline/2
		(phoenix 1.5.6) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
		(petree_api 0.1.0) lib/petree_api_web/endpoint.ex:1: PetreeApiWeb.Endpoint.plug_builder_call/2
		(petree_api 0.1.0) lib/plug/debugger.ex:132: PetreeApiWeb.Endpoint."call (overridable 3)"/2
		(petree_api 0.1.0) lib/petree_api_web/endpoint.ex:1: PetreeApiWeb.Endpoint.call/2
		(phoenix 1.5.6) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
		(cowboy 2.8.0) /app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
		(cowboy 2.8.0) /app/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
		(cowboy 2.8.0) /app/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3
		(stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by omohokcoj** [comment]
@eduardomrocha thanks for reporting this, it has been fixed in the newest version (0.7.4)
